version: "3.7"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./Scores.txt:/app/Scores.txt
    environment:
      FLASK_APP: MainScores.py
    command: flask run --host=0.0.0.0

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
